### ISSUE TITLE
Preview pane not displaying map

### ISSUE THREAD

**Issue by tkershaw** [qgis2web/qgis2web#1146]
My preview pane is not displaying my webmap preview
When i click "Update Preview" (for either OpenLayers or Leaflet) the preview pane quickly flickers a white box then shows just the grey background

![Image](https://github.com/user-attachments/assets/bbfe602c-0e1f-45fb-a83d-cd42ca2f2d0d)

I am able to export but i would like to use the preview function

I am using qgis2web v3.25.1
When i revert to qgis2web v3.21.0 the preview pane successfully displays the map preview but i would like to use the latest version

![Image](https://github.com/user-attachments/assets/af3971b7-7619-4676-af1d-a8b1f16a3e8b)

Other system info

![Image](https://github.com/user-attachments/assets/90248da0-3b18-49d5-9d67-e368863d8843)

Thanks for any help you can provide!

**Comment by andreaordonselli** [comment]
Can you provide your qgis project uploading it here in a zip?

**Comment by tkershaw** [comment]
[qgis2web_debug.zip](https://github.com/user-attachments/files/19574626/qgis2web_debug.zip)

**Comment by idshklein** [comment]
same problem here

**Comment by andreaordonselli** [comment]
In version [3.26.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.25.1) the issue discussed in this thread is resolved. The update will soon be available in the QGIS plugin repository.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Thank you for using the plugin.

Best regards.

**Comment by tkershaw** [comment]
I am having the same issue with the latest version of qgis2web 3.26.0

![Image](https://github.com/user-attachments/assets/0ceedd19-cfa7-4c0c-8559-3ca6db39b31b)

My log messages show the following

2025-05-06T08:29:22     WARNING    warning:C:\Users/…QGIS3\profiles\default/python/plugins\qgis2web\leafletLayerScripts.py:452: DeprecationWarning: QgsMapLayer.attributionUrl() is deprecated
              attrUrl = layer.attributionUrl()
             
             traceback: File "C:\Users/…/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 483, in previewMap
              preview_file = self.createPreview()
              File "C:\Users/…/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 445, in createPreview
              preview_file = writer.write(self.iface, dest_folder=utils.tempFolder()).index_file
              File "C:\Users/…/QGIS3\profiles\default/python/plugins\qgis2web\leafletWriter.py", line 94, in write
              self.preview_file = self.writeLeaflet(
              File "C:\Users/…/QGIS3\profiles\default/python/plugins\qgis2web\leafletWriter.py", line 278, in writeLeaflet
              useOSMB) = writeVectorLayer(layer, safeLayerName,
              File "C:\Users/…/QGIS3\profiles\default/python/plugins\qgis2web\leafletLayerScripts.py", line 135, in writeVectorLayer
              useMultiStyle) = getLayer(layer, renderer, safeLayerName, interactive,
              File "C:\Users/…/QGIS3\profiles\default/python/plugins\qgis2web\leafletLayerScripts.py", line 407, in getLayer
              useMultiStyle) = nonPointLayer(layer, safeLayerName, interactive,
              File "C:\Users/…/QGIS3\profiles\default/python/plugins\qgis2web\leafletLayerScripts.py", line 452, in nonPointLayer
              attrUrl = layer.attributionUrl()
             
I also have the same issue with qgis2o.gis

**Comment by andreaordonselli** [comment]
Hi, in this discussion you showed that you have QGIS 3.40, do you still have this version or have updated QGIS?

**Comment by tkershaw** [comment]
Still have the issue with QGIS v3.42.2

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.42.2-Münster</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/402273f8c2">402273f8c2</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.13</td></tr><tr><td>Python version</td><td>3.12.10</td></tr><tr><td>GDAL version</td><td>3.10.3</td></tr><tr><td>PROJ version</td><td>9.6.0</td></tr><tr><td>EPSG Registry database version</td><td>v12.004 (2025-03-02)</td></tr><tr><td>GEOS version</td><td>3.13.1-CAPI-1.19.2</td></tr><tr><td>SQLite version</td><td>3.46.1</td></tr><tr><td>PDAL version</td><td>2.8.3</td></tr><tr><td>PostgreSQL client version</td><td>17.3</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.3.0</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>Windows 11 Version 2009</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>a00_qpip</td><td>1.1.0</td></tr><tr><td>cartolinegen</td><td>3.2.2</td></tr><tr><td>compare_attributes</td><td>1.0</td></tr><tr><td>contour</td><td>2.0.15</td></tr><tr><td>coordinates_converter</td><td>1.0</td></tr><tr><td>coordinator</td><td>0.4</td></tr><tr><td>crayfish</td><td>3.6.0</td></tr><tr><td>data_sources_panel</td><td>0.2.1</td></tr><tr><td>easyfeatureselection</td><td>1.0.1</td></tr><tr><td>FilePath</td><td>0.3</td></tr><tr><td>file_management</td><td>0.1</td></tr><tr><td>geetimeseriesexplorer</td><td>2.0</td></tr><tr><td>GroupStats</td><td>2.2.7</td></tr><tr><td>IPyConsole</td><td>version 2.1</td></tr><tr><td>latlontools</td><td>3.7.4</td></tr><tr><td>layout_panel-main</td><td>0.3</td></tr><tr><td>LecoS</td><td>3.0.1</td></tr><tr><td>MapsPrinter</td><td>1.0</td></tr><tr><td>mapswipetool_plugin</td><td>1.3</td></tr><tr><td>opacity_set_01</td><td>0.2</td></tr><tr><td>PluginLoadTimes</td><td>4.1.2</td></tr><tr><td>postgis_toolbox</td><td>1.2</td></tr><tr><td>profiletool</td><td>4.3.2</td></tr><tr><td>QGISSortAndNumber-master</td><td>1.0</td></tr><tr><td>QuickWKT</td><td>3.1</td></tr><tr><td>quick_map_services</td><td>0.21.2</td></tr><tr><td>searchlayers</td><td>3.1.1</td></tr><tr><td>send2google_earth</td><td>0.4.0</td></tr><tr><td>Serval</td><td>3.32.0</td></tr><tr><td>StreetView</td><td>3.3</td></tr><tr><td>Submission</td><td>0.10</td></tr><tr><td>thanks_for_the_coffee</td><td>2.25.0</td></tr><tr><td>timemanager</td><td>3.7</td></tr><tr><td>track_profile_2_web</td><td>1.3</td></tr><tr><td>trail_elevation_stats</td><td>0.2</td></tr><tr><td>usgs_stream_mapper</td><td>0.4</td></tr><tr><td>valuetool</td><td>3.0.19</td></tr><tr><td>zoomtopaste</td><td>3.0.3</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>processing</td><td>2.12.99</td></tr><tr><td>qgis2web</td><td>3.26.0</td></tr></table>

**Comment by tkershaw** [comment]
Still having same issue with 3.40.6

![Image](https://github.com/user-attachments/assets/83f0f6bd-2fea-40fe-b637-6bd66cb64389)

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.40.6-Bratislava</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/5d7f6a3e26">5d7f6a3e26</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.13</td></tr><tr><td>Python version</td><td>3.12.10</td></tr><tr><td>GDAL version</td><td>3.10.3</td></tr><tr><td>PROJ version</td><td>9.6.0</td></tr><tr><td>EPSG Registry database version</td><td>v12.004 (2025-03-02)</td></tr><tr><td>GEOS version</td><td>3.13.1-CAPI-1.19.2</td></tr><tr><td>SQLite version</td><td>3.46.1</td></tr><tr><td>PDAL version</td><td>2.8.3</td></tr><tr><td>PostgreSQL client version</td><td>unknown</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.3.0</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>Windows 11 Version 2009</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>a00_qpip</td><td>1.1.0</td></tr><tr><td>cartolinegen</td><td>3.2.2</td></tr><tr><td>compare_attributes</td><td>1.0</td></tr><tr><td>contour</td><td>2.0.15</td></tr><tr><td>coordinates_converter</td><td>1.0</td></tr><tr><td>coordinator</td><td>0.4</td></tr><tr><td>crayfish</td><td>3.6.0</td></tr><tr><td>data_sources_panel</td><td>0.2.1</td></tr><tr><td>easyfeatureselection</td><td>1.0.1</td></tr><tr><td>FilePath</td><td>0.3</td></tr><tr><td>file_management</td><td>0.1</td></tr><tr><td>geetimeseriesexplorer</td><td>2.0</td></tr><tr><td>GroupStats</td><td>2.2.7</td></tr><tr><td>IPyConsole</td><td>version 2.1</td></tr><tr><td>latlontools</td><td>3.7.4</td></tr><tr><td>layout_panel-main</td><td>0.3</td></tr><tr><td>LecoS</td><td>3.0.1</td></tr><tr><td>MapsPrinter</td><td>1.0</td></tr><tr><td>mapswipetool_plugin</td><td>1.3</td></tr><tr><td>opacity_set_01</td><td>0.2</td></tr><tr><td>PluginLoadTimes</td><td>4.1.2</td></tr><tr><td>postgis_toolbox</td><td>1.2</td></tr><tr><td>profiletool</td><td>4.3.2</td></tr><tr><td>QGISSortAndNumber-master</td><td>1.0</td></tr><tr><td>QuickWKT</td><td>3.1</td></tr><tr><td>quick_map_services</td><td>0.21.2</td></tr><tr><td>searchlayers</td><td>3.1.1</td></tr><tr><td>send2google_earth</td><td>0.4.0</td></tr><tr><td>Serval</td><td>3.32.0</td></tr><tr><td>StreetView</td><td>3.3</td></tr><tr><td>Submission</td><td>0.10</td></tr><tr><td>thanks_for_the_coffee</td><td>2.25.0</td></tr><tr><td>timemanager</td><td>3.7</td></tr><tr><td>track_profile_2_web</td><td>1.3</td></tr><tr><td>trail_elevation_stats</td><td>0.2</td></tr><tr><td>usgs_stream_mapper</td><td>0.4</td></tr><tr><td>valuetool</td><td>3.0.19</td></tr><tr><td>zoomtopaste</td><td>3.0.3</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>processing</td><td>2.12.99</td></tr><tr><td>qgis2web</td><td>3.26.0</td></tr></table>

**Comment by andreaordonselli** [comment]
I can't replicate the problem. Your example project is exported correctly with QGIS 3.40.0 using OpenLayers export. There are issues with Leaflet export, but they occur after the export and do not provide the error you mentioned: `QgsMapLayer.attributionUrl()` is deprecated." Please create a new QGIS user, install only qgis2web, and try again. Let me know if you resolve the issue.
`Settings > User profiles > New Profile`

**Comment by andreaordonselli** [comment]
I can't understand why you're getting this error.
Do you receive it only when you click 'preview' or also when you click 'export'?
Did you install QGIS using the `.msi` package or through the `osgeo4w` package manager?  
You should try manually installing the PyQtWebEngine package via osgeo4w.

**Comment by andreaordonselli** [comment]
Sono contento che tu abbia risolto.
Ti ringrazio molto per la donazione, è essenziale per il mantenimento del progetto.
