### ISSUE TITLE
Popup size - Solution for bug #493

### ISSUE THREAD

**Issue by greyeagle** [qgis2web/qgis2web#532]
Bug #493 was closed without solution. I am sorry I do not really know how to make a pull request since I am fairly new to GitHub. 
Anyway this is my solution and I hope it will help someone:
For **OpenLayers**: 
In the file qgis2web/resources/qgis2web.css change .ol-popup to 
```css
.ol-popup {
    display: none;
    position: absolute;
    background-color: white;
    -moz-box-shadow: 0 1px 4px rgba(0,0,0,0.2);
    -webkit-filter: drop-shadow(0 1px 4px rgba(0,0,0,0.2));
    filter: drop-shadow(0 1px 4px rgba(0,0,0,0.2));
    padding: 15px;
    border-radius: 10px;
    border: 1px solid #cccccc;
    bottom: 12px;
    left: -50px;   
    height: auto;
    width: auto;
    min-width: 100px;     
    overflow: auto;
    max-height: 250px;
}
```
Mind the last two lines that make the popup scrollable and limit the size to something sensible.

For **Leaflet**:
This is somewhat more complicated and involves changes in python:
In the file qgis2web/leafletScriptStrings.py change popFuncsScript to:
```python
def popFuncsScript(table):
    table = table.encode("utf-8")
    _style = {'maxHeight':'250'}
    popFuncs = """
            var popupContent = {table};
            var style = {_style};
            layer.bindPopup(popupContent,style);""".format(table=table, _style=_style)
    return popFuncs
```
Mind setting the **maxHeight** which causes Leaflet to make the popup scrollable and limits it to a reasonable size.
Additionally in qgis2web/leafletFileScripts.py I changed the following css styles to:
```css
.leaflet-container {
    background: #fff;
    padding-right: 10px;
}
.leaflet-popup-content {
    width:auto !important;
    padding-right:10px;
}
```

I hope this will somehow be helpful. I also had tons of attributes and was lost.

**Comment by tomchadwin** [comment]
Many thanks for this! I've formatted the text in your comment to get the line breaks back. @misterphilipj, does this solve your problem? I'd also be interested what effect this has on popups with little data in them (hopefully no effect).

**Comment by greyeagle** [comment]
Wow, you are fast! I just found out myself how to properly format the code. Thanks for doing this for me already. Did not expect this lightning fast response.

**Comment by greyeagle** [comment]
I just tested with a dataset containing only few attributes and it has no effect neither in Leaflet nor in OpenLayers. 
So no drawbacks to this solution as far as I can see.

**Comment by tomchadwin** [comment]
Thanks for testing so quickly. If you want some help doing a PR on Github, I'm very happy indeed to help - if I make those changes myself, you won't have much evidence that it was your work, as I'll be listed as tjhe author. Let me know if you want to have a go.

**Comment by greyeagle** [comment]
I do not mind the credit actually, main thing is it solves the issue. Anyhow it would be interesting to see how it works to make a PR just in case I need it one day. So where do I start? Is there some documentation I should start reading at?

**Comment by tomchadwin** [comment]
Hopefully quite simple. Try this:

1. Click the "Fork" button, top-right on this page to create your own copy
2. Confirm that you are now browsing https://github.com/greyeagle/qgis2web
3. Click "Code", top-left
4. Click the file you want to change
5. Click the edit pencil, top-right of the code window
6. Make your changes and save them
7. When you have made all your changes, click "Pull requests", and then "New pull request"
8. Click the text link "compare across forks"
9. For the base fork, choose "tomchadwin/qgis2web", base: "master"
10. For the head fork, choose "greyeagle/qgis2web", base:"master"
11. Confirm that you can see your changes listed below
12. Click "Create new pull request"

See how you go with that, and post any questions here.

**Comment by greyeagle** [comment]
Thanks for the step by step. I will try later this week. Have to fix a few bugs in my jobs project first ;-)

**Comment by tomchadwin** [comment]
Are you still interested in trying this out yourself, or shall I code it up? I'll still credit you in the changelog.

**Comment by tomchadwin** [comment]
I've noticed that your OpenLayers fix is already in place, courtesy of @OlaKov, though she chose 400px rather than 250px. Looking at Leaflet now.

**Comment by tomchadwin** [comment]
Fix committed to master. Please test.

**Comment by tomchadwin** [comment]
OK, although I've implemented it, I'm not sure it's quite right. If there is too much data for the popup, we get a vertical scrollbar, which is good, but the presence of that scrollbar makes a horizontal scrollbar appear, which is not wanted. I've checked the Leaflet API, and it doesn't expose `overflow-x` or `overflow-y`, so I guess we'd have to add our own class and attach via the `className` option.

**Comment by tomchadwin** [comment]
Hrm, perhaps it's OK. I'm not seeing the horizontal scrollbar as often as I expected. I think it's browser-dependent. Will close for now, but do reopen if the issue is still ongoing.

**Comment by greyeagle** [comment]
Uhh, I completely got over this! Sorry so much. Glad it got dome anyhow.

**Comment by riccardoklinger** [comment]
Sorry for re-opening this. I think the setting max-width to auto !important is causing some issues both on FF and IE:
without the important! flag in the css, this still get the needed width:
![grafik](https://user-images.githubusercontent.com/7377897/62054899-d1c8c380-b21a-11e9-8309-239b14ecc14f.png)
with the important flag it looks not as good:
![grafik](https://user-images.githubusercontent.com/7377897/62055032-1ce2d680-b21b-11e9-9dd0-9bc71121c081.png)

**Comment by andreaordonselli** [comment]
I have just released version [3.18.1](https://github.com/qgis2web/qgis2web/releases/tag/v3.18.1), which fixes the issues discussed in this thread. Shortly, the update will be available within the QGIS plugin repository.

I am closing the thread and kindly ask you to reopen it if the update does not meet your expectations. Thank you for using the plugin.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Best regards.
